# Generated by Django 3.2.14 on 2022-07-29 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_rename_body_review_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='review_content',
        ),
    ]
