# Generated by Django 3.2.14 on 2022-07-08 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0003_auto_20220707_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
    ]
