# Generated by Django 3.2.14 on 2022-07-25 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0006_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='date',
            new_name='requested_date',
        ),
    ]
