# Generated by Django 3.2.14 on 2022-07-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0007_rename_date_booking_requested_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('artist', models.CharField(choices=[('becky', 'Becky Johnson'), ('alex', 'Alex Anderson'), ('john', 'John Masters'), ('alison', 'Alison Taylor'), ('jasmine', 'Jasmine Evans'), ('david', 'David Walker'), ('any', 'Any')], default='any', max_length=20)),
                ('body', models.TextField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
