# Generated by Django 3.2.14 on 2022-07-25 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0008_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='created_on',
            new_name='sent',
        ),
    ]
