# Generated by Django 3.2.14 on 2022-07-26 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0009_rename_created_on_review_sent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
